name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "version/*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history including tags
      - uses: jdx/mise-action@v2

      - run: pnpm install

      - run: ./scripts/do-release.js
